### ISSUE TITLE
AttributeError: module 'pyMeow' has no attribute 'new_color_float'. Did you mean: 'new_color_hex'?

### ISSUE THREAD

**Issue by githubianuser** [g0ldyy/NameIt#10]
AttributeError: module 'pyMeow' has no attribute 'new_color_float'. Did you mean: 'new_color_hex'?

File "c:\Users\TEST\Desktop\CS2_TriggerBot-main\CS2_TriggerBot-main\comp\pyMeow\main.py", line 148, in __init__
    self.espColor = pm.new_color_float(self.config["esp"]["color"]["r"], self.config["esp"]["color"]["g"], self.config["esp"]["color"]["b"], self.config["esp"]["color"]["a"])

when trying to build from source.

**Comment by githubianuser** [comment]
I build pyMeow properly, are you able to include your build of pyMeow in the source? I am having troubles building.

**Comment by g0ldyy** [comment]
you have to build latest version of pymeow

**Comment by g0ldyy** [comment]
I added pymeow.pyd to the repo.
