### ISSUE TITLE
Triggerkey set to None not available, Overlay sometimes Crash, Not working at all in Deathmatch

### ISSUE THREAD

**Issue by L4ZY7331** [g0ldyy/NameIt#14]
First of all, i wanna say its amazing work. Its really fun to use men!!!

**Seems fixed in 1.0.3.
[My major issue is that sometimes the Overlay crashes and whenever i try to restart the Bot while Ingame i need multiple trys.]**
**[Second issue is, in Deathmatch its not working at all for me.]**

Third thing is just personal. I would really like an option to set the Triggerbot ON but requires NO Triggerkey.

Thanks for your work! Waiting for an update.

**edit: just saw i was on v1.0. just updated to 1.0.3.**

**Comment by g0ldyy** [comment]
Hey mate, I need to motivate myself to continue this project ngl but it's coming soon! I will probably have to redo it from scratch because it's not that optimized. For your TriggerBot problem, I will add two modes : Auto/Toggle.

**Comment by L4ZY7331** [comment]
thanks men, you are the best. would really awesome to get something like
that for the finals too, ive heard python is fine there also

Am Fr., 22. März 2024 um 23:40 Uhr schrieb Goldy ***@***.***>:
