### ISSUE TITLE
Error: "Can't retrieve offsets. Press any key to exit!"

### ISSUE THREAD

**Issue by liberteryen** [g0ldyy/NameIt#17]
![resim](https://github.com/g0ldyy/NameIt/assets/84645312/b2c7993e-428c-4cb1-9c54-147710aa7c03)
I installed Windows 11 to use this cheat. I'm getting an error like this. The error occurred after opening CS2.
Then I closed CS2.

(I wrote using google translate)

**Comment by ImInTheICU** [comment]
Hello again @Hhk78 :wave:
So our "releases" tab on Github is not currently updated it's about 5-6 major updates behind.
If you could run from source, or wait for either me or @g0ldyy to push a new release build (not sure if it will happen) then it should work.
We have install instructions inside the README file.

**Comment by liberteryen** [comment]
Thank you for your interest. I will do as you say. I hope it works.
I used google translate()

**Comment by Hhk78** [comment]
```C:\Users\h\Downloads\NameIt-main\NameIt-main>python3 main.py
Traceback (most recent call last):
  File "C:\Users\h\Downloads\NameIt-main\NameIt-main\main.py", line 551, in <module>
    nameItClass = NameIt()
                  ^^^^^^^^
  File "C:\Users\h\Downloads\NameIt-main\NameIt-main\main.py", line 148, in __init__
    self.espColor = pm.new_color_float(self.config["esp"]["color"]["r"], self.config["esp"]["color"]["g"], self.config["esp"]["color"]["b"], self.config["esp"]["color"]["a"])
                    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyMeow' has no attribute 'new_color_float'. Did you mean: 'new_color_hex'?```

İ have Error.

**Comment by liberteryen** [comment]
I have error.
![resim](https://github.com/g0ldyy/NameIt/assets/84645312/6eac3bbe-b486-4ce7-a420-be80ec33a9b4)

**Comment by ImInTheICU** [comment]
You'll need to build the latest version of PyMeow.
And replace the current pyMeow.pyd with the new one you build from pyMeow's source. ( we have instructions in our README file on how to do this ).

**Comment by liberteryen** [comment]
I already did what you said

**Comment by liberteryen** [comment]
Is there any progress? I compiled a few more times but this error persists every time.

**Comment by g0ldyy** [comment]
fixed in latest release.

**Comment by liberteryen** [comment]
thank you so much

**Comment by g0ldyy** [comment]
> thank you so much

np :)
