### ISSUE TITLE
 For some reason I have a black background #bug

### ISSUE THREAD

**Issue by krysjak** [g0ldyy/NameIt#2]
![image](https://github.com/g0ldyy/NameIt/assets/142928104/03e433be-17a5-4c51-ad4b-86f432f22f98)

For some reason I have a black background

**Comment by krysjak** [comment]
help

**Comment by g0ldyy** [comment]
set cs2 to windowed fullscreen and click on the black thing

**Comment by krysjak** [comment]
put it on the window in full screen, went to the window with a black background, clicked on it and the black one was still there
[Uploading bandicam 2024-01-07 14-10-07-573.zip…]()

**Comment by g0ldyy** [comment]
add me on Discord so I can help you Goldy#1255

**Comment by krysjak** [comment]
my ds korobochka

**Comment by g0ldyy** [comment]
fixed in latest version.
