### ISSUE TITLE
Black Screen and Broken ESP

### ISSUE THREAD

**Issue by jdsmithmv** [g0ldyy/NameIt#20]
Is this project still working? Using Python for this type of project is awesome and I'd enjoy contributing to this repo if I can get it running locally. 

When I start main.py, my screen goes black with only the FPS showing in the top left corner. I read the other closed issues and tried running in Fullscreen Windowed mode but had no luck. 

Is there a fix to get the GUI overlay to show?

**Comment by ImInTheICU** [comment]
Duplicate issue.
https://github.com/g0ldyy/NameIt/issues/2
https://github.com/g0ldyy/NameIt/issues/9
TL:DR WIN+TAB and make sure your mode is windowed full screen.
