### ISSUE TITLE
esp isnt attached to enemies

### ISSUE THREAD

**Issue by Maurisio12345** [g0ldyy/NameIt#22]
![Näyttökuva 2024-06-02 023757](https://github.com/g0ldyy/NameIt/assets/110994641/9b058074-5f1c-4db4-a911-63bccfeba0b9)

**Comment by g0ldyy** [comment]
yeah, latest update broke it
if anyone got the time to update it, feel free to do it!

**Comment by ImInTheICU** [comment]
Do we know exactly what the problem is?
I'm free to make a PR just trying to figure out how this even happened.
