### ISSUE TITLE
Tested new version. ESP still not attached 

### ISSUE THREAD

**Issue by L4ZY7331** [g0ldyy/NameIt#25]
Hey guys,

was really happy to see an update here. Sadly i tried the latest version main.py and still esp wont work proper. It wont even show in Crosshair test map at bots and in a warmup match esp is still not attached to enemies and just floating around.

can u check again?

apreciate ur work

**Comment by g0ldyy** [comment]
@ImInTheICU

**Comment by ImInTheICU** [comment]
Could be offset(s)?
Let me check it out.

**Comment by ImInTheICU** [comment]
https://github.com/g0ldyy/NameIt/pull/26 Should be fixed. @g0ldyy @Awzum731
