### ISSUE TITLE
pm.new_color_float

### ISSUE THREAD

**Issue by DrYusuff** [g0ldyy/NameIt#3]
I got an error like this can u help?
self.espColor = pm.new_color_float(self.config["esp"]["color"]["r"], self.config["esp"]["color"]["g"],
                    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyMeow' has no attribute 'new_color_float'. Did you mean: 'new_color_hex'?

**Comment by g0ldyy** [comment]
you need latest pymeow version to run source code (you have to build it yourself using nim)

**Comment by DrYusuff** [comment]
thanks for response
i did build mymeow actually.As you see it is not saying module didn't found...
i don't know what is nim by the way(i just started learning python, hack is just for fun on the way)

**Comment by DrYusuff** [comment]
thank you bro
i tried what said and just messed up everything 
my purpose wasn't hack i was just learning programming but i will check again later
