### ISSUE TITLE
Black window

### ISSUE THREAD

**Issue by Enmton** [g0ldyy/NameIt#9]
Hello,
every time i start it, the gui comes up and a new window pops up over the game. It shows the ESP but unfortunately the rest is black.
so a black window 
How can I fix this?
i have amd cpu & gpu

tried in window mode and borderless

**Comment by ImInTheICU** [comment]
Hello Enmton!
I think @g0ldyy has addressed this issue but I'm not quite sure If he even added his patch.
In the meantime you should be able to ALT+TAB back into the CS2 process.
The "blackscreen" is just a transparent overlay.

Edit-1: You might also want to try Fullscreen Windowed for CS2.

Thanks for reaching out 
- Pingu.

**Comment by Enmton** [comment]
when I use Fullscreen, it no longer overlays the screen.

As soon as I change the modes, it goes black again.
unfortunately i can't say if fullscreen mode works completely because of the new updates.
But since it gets these offsets itself i don't think it works otherwise i should be able to see yes opponents in fullscreen

**Comment by ImInTheICU** [comment]
Try the newest **source code** version on fullscreen windowed.
Keep in mind every update it will take around 1-3 hours for the new offsets to be pulled since we use A2X dumper.
If you need help compiling or running from the source you can check our README.

**Comment by Enmton** [comment]
c:\Users\****\Downloads\NameIt-main\NameIt-main>C:\Users\****\Downloads\NameIt-main\NameIt-main\main.py
Traceback (most recent call last):
  File "C:\Users\****\Downloads\NameIt-main\NameIt-main\main.py", line 548, in <module>
    nameItClass = NameIt()
                  ^^^^^^^^
  File "C:\Users\****\Downloads\NameIt-main\NameIt-main\main.py", line 148, in __init__
    self.espColor = pm.new_color_float(self.config["esp"]["color"]["r"], self.config["esp"]["color"]["g"], self.config["esp"]["color"]["b"], self.config["esp"]["color"]["a"])
                    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyMeow' has no attribute 'new_color_float'. Did you mean: 'new_color_hex'?

**Comment by ImInTheICU** [comment]
You need the newest version of PyMeow.

**Comment by Enmton** [comment]
okay thats help :) 
but he didnt update the offstes.
i see fps overlay and trigger works but the esp dont work

**Comment by g0ldyy** [comment]
offsets are updated automatically.
